id: IBC510934
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:33:42.614709
last_modified: 2023-02-10 00:33:42.614806
source_metadata:
  title: 'Nāgārjuna: Vigrahavyāvartanīvṛtti'
  language: en
bases:
  319A:
    base_file: 319A.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
